CREATE TABLE [tbl_wrk_Cover_Pct_Wetland_GS] (
  [UnitCode] VARCHAR (4),
  [Stream_Name] VARCHAR (50),
  [PlotID] SHORT ,
  [Geomorph] VARCHAR (50),
  [FACL] DOUBLE ,
  [FACA] DOUBLE ,
  [FACUL] DOUBLE ,
  [FACUA] DOUBLE ,
  [FACWL] DOUBLE ,
  [FACWA] DOUBLE ,
  [OBLL] DOUBLE ,
  [OBLA] DOUBLE ,
  [UPLL] DOUBLE ,
  [UPLA] DOUBLE ,
  [CULTL] DOUBLE ,
  [CULTA] DOUBLE ,
  [Total_Live] DOUBLE ,
  [Total_Cover] DOUBLE 
)
