CREATE TABLE [tbl_wrk_Tree_Size_Class] (
  [UnitCode] VARCHAR (4),
  [Stream_Name] VARCHAR (50),
  [PlotID] SHORT ,
  [Visit_Year] SHORT ,
  [Transect] SHORT ,
  [Species] VARCHAR (25),
  [Total_Trees] SHORT ,
  [Total_Seedlings] SHORT ,
  [Live_5] SHORT ,
  [Live_10] SHORT ,
  [Live_15] SHORT ,
  [Live_20] SHORT ,
  [Live_30] SHORT ,
  [Live_40] SHORT ,
  [Live_50] SHORT ,
  [Live_Over_50] SHORT ,
  [All_5] SHORT ,
  [All_10] SHORT ,
  [All_15] SHORT ,
  [All_20] SHORT ,
  [All_30] SHORT ,
  [All_40] SHORT ,
  [All_50] SHORT ,
  [All_Over_50] SHORT 
)
