CREATE TABLE [tbl_wrk_Tree_Density] (
  [UnitCode] VARCHAR (4),
  [Stream_Name] VARCHAR (50),
  [Visit_Year] SHORT ,
  [PlotID] SHORT ,
  [Seedlings_ha] DOUBLE ,
  [Live_Total_ha] DOUBLE ,
  [Live_5_ha] DOUBLE ,
  [Live_10_ha] DOUBLE ,
  [Live_15_ha] DOUBLE ,
  [Live_20_ha] DOUBLE ,
  [Live_30_ha] DOUBLE ,
  [Live_40_ha] DOUBLE ,
  [Live_50_ha] DOUBLE ,
  [Live_Over_50_ha] DOUBLE ,
  [All_Total_ha] DOUBLE ,
  [All_5_ha] DOUBLE ,
  [All_10_ha] DOUBLE ,
  [All_15_ha] DOUBLE ,
  [All_20_ha] DOUBLE ,
  [All_30_ha] DOUBLE ,
  [All_40_ha] DOUBLE ,
  [All_50_ha] DOUBLE ,
  [All_Over_50_ha] DOUBLE 
)
