CREATE TABLE [tbl_wrk_Cover_Pct_Surface] (
  [UnitCode] VARCHAR (4),
  [Stream_Name] VARCHAR (50),
  [PlotID] SHORT ,
  [Visit_Year] SHORT ,
  [BL] DOUBLE ,
  [BR] DOUBLE ,
  [BSC] DOUBLE ,
  [CB] DOUBLE ,
  [F] DOUBLE ,
  [GC] DOUBLE ,
  [GF] DOUBLE ,
  [L] DOUBLE ,
  [NR] DOUBLE ,
  [SL] DOUBLE ,
  [SW] DOUBLE ,
  [WA] DOUBLE ,
  [WD] DOUBLE ,
  [Ant] DOUBLE ,
  [Auto] DOUBLE ,
  [Bike] DOUBLE ,
  [Camp] DOUBLE ,
  [Flood] DOUBLE ,
  [Graze] DOUBLE ,
  [Other] DOUBLE ,
  [Trail] DOUBLE 
)
